/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/RecipeUpdateForm copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/HelloWorld.vue')['default']
    RecipeDashboard: typeof import('./src/components/RecipeDashboard.vue')['default']
    'RecipeDashboard.vue': typeof import('./src/components/RecipeDashboard.vue.vue')['default']
    RecipeUpdateForm: typeof import('./src/components/RecipeUpdateForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
